// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Reservation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250316013950_dcncvjeevjevb")]
    partial class dcncvjeevjevb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Reservation.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 30,
                            CIN = "CIN1",
                            Nom = "ClientNom1",
                            Prenom = "ClientPrenom1"
                        },
                        new
                        {
                            Id = 2,
                            Age = 32,
                            CIN = "CIN2",
                            Nom = "ClientNom2",
                            Prenom = "ClientPrenom2"
                        },
                        new
                        {
                            Id = 3,
                            Age = 28,
                            CIN = "CIN3",
                            Nom = "ClientNom3",
                            Prenom = "ClientPrenom3"
                        },
                        new
                        {
                            Id = 4,
                            Age = 45,
                            CIN = "CIN4",
                            Nom = "ClientNom4",
                            Prenom = "ClientPrenom4"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Gestionnaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnneeRecrutement")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Gestionnaires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AnneeRecrutement = 2018,
                            Code = "GEST123",
                            Nom = "Ali"
                        },
                        new
                        {
                            Id = 2,
                            AnneeRecrutement = 2020,
                            Code = "GEST456",
                            Nom = "Nadia"
                        },
                        new
                        {
                            Id = 3,
                            AnneeRecrutement = 2021,
                            Code = "GEST789",
                            Nom = "Yassine"
                        },
                        new
                        {
                            Id = 4,
                            AnneeRecrutement = 2019,
                            Code = "GEST999",
                            Nom = "Omar"
                        },
                        new
                        {
                            Id = 5,
                            AnneeRecrutement = 2022,
                            Code = "GEST222",
                            Nom = "Sofia"
                        });
                });

            modelBuilder.Entity("Reservation.Models.Reservations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateReservation")
                        .HasColumnType("datetime2");

                    b.Property<int>("Etat")
                        .HasColumnType("int");

                    b.Property<int>("VolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("VolId");

                    b.ToTable("Reservations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClientId = 1,
                            DateReservation = new DateTime(2024, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 1,
                            VolId = 1
                        },
                        new
                        {
                            Id = 2,
                            ClientId = 2,
                            DateReservation = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 2
                        },
                        new
                        {
                            Id = 3,
                            ClientId = 3,
                            DateReservation = new DateTime(2024, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 1,
                            VolId = 3
                        },
                        new
                        {
                            Id = 4,
                            ClientId = 4,
                            DateReservation = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 4
                        },
                        new
                        {
                            Id = 5,
                            ClientId = 4,
                            DateReservation = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 3
                        },
                        new
                        {
                            Id = 6,
                            ClientId = 4,
                            DateReservation = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 2
                        },
                        new
                        {
                            Id = 7,
                            ClientId = 4,
                            DateReservation = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 1
                        },
                        new
                        {
                            Id = 8,
                            ClientId = 4,
                            DateReservation = new DateTime(2024, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Etat = 0,
                            VolId = 4
                        });
                });

            modelBuilder.Entity("Reservation.Models.Vol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateArrivee")
                        .HasColumnType("datetime2");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NombrePlacesMax")
                        .HasColumnType("int");

                    b.Property<int>("PlacesDisponibles")
                        .HasColumnType("int");

                    b.Property<int>("Prix")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vols");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateArrivee = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Depart = "Casablanca",
                            Destination = "Paris",
                            NombrePlacesMax = 200,
                            PlacesDisponibles = 50,
                            Prix = 1500
                        },
                        new
                        {
                            Id = 2,
                            DateArrivee = new DateTime(2024, 7, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Depart = "Marrakech",
                            Destination = "New York",
                            NombrePlacesMax = 300,
                            PlacesDisponibles = 100,
                            Prix = 3500
                        },
                        new
                        {
                            Id = 3,
                            DateArrivee = new DateTime(2024, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Depart = "Rabat",
                            Destination = "Dubai",
                            NombrePlacesMax = 250,
                            PlacesDisponibles = 150,
                            Prix = 2500
                        },
                        new
                        {
                            Id = 4,
                            DateArrivee = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Depart = "Casablanca",
                            Destination = "Tokyo",
                            NombrePlacesMax = 150,
                            PlacesDisponibles = 80,
                            Prix = 4500
                        },
                        new
                        {
                            Id = 5,
                            DateArrivee = new DateTime(2024, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Depart = "Marrakech",
                            Destination = "London",
                            NombrePlacesMax = 180,
                            PlacesDisponibles = 60,
                            Prix = 2000
                        });
                });

            modelBuilder.Entity("Reservation.Models.Reservations", b =>
                {
                    b.HasOne("Reservation.Models.Client", "Client")
                        .WithMany("Reservations")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Reservation.Models.Vol", "Vol")
                        .WithMany("Reservations")
                        .HasForeignKey("VolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Vol");
                });

            modelBuilder.Entity("Reservation.Models.Client", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Reservation.Models.Vol", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
